<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <DisableFody>true</DisableFody>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Anotar.NServiceBus\Anotar.NServiceBus.csproj" />
    <PackageReference Include="NServiceBus" />
  </ItemGroup>
</Project>