<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net48;net8.0</TargetFrameworks>
    <DisableFody>true</DisableFody>
    <OutputType>Exe</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <Using Include="System.Threading.Tasks" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Common.Logging" />
    <PackageReference Include="FodyHelpers" />
    <PackageReference Include="TUnit.Core" />
    <PackageReference Include="TUnit.Assertions" />
    <PackageReference Include="TUnit.Engine" />
    <PackageReference Include="Verify.TUnit" />
    <PackageReference Include="Microsoft.CSharp" />
    <ProjectReference Include="..\Anotar.CommonLogging.Fody\Anotar.CommonLogging.Fody.csproj" />
    <ProjectReference Include="..\Anotar.CommonLogging\Anotar.CommonLogging.csproj" />
    <ProjectReference Include="..\AssemblyToProcess\AssemblyToProcess.csproj" />
  </ItemGroup>
</Project>