<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <DisableFody>true</DisableFody>
    <OutputType>Exe</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <Using Include="System.Threading.Tasks" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="FodyHelpers" />
    <PackageReference Include="NServiceBus" />
    <PackageReference Include="TUnit.Core" />
    <PackageReference Include="TUnit.Assertions" />
    <PackageReference Include="TUnit.Engine" />
    <PackageReference Include="Verify.TUnit" />
    <ProjectReference Include="..\Anotar.NServiceBus.Fody\Anotar.NServiceBus.Fody.csproj" />
    <ProjectReference Include="..\Anotar.NServiceBus\Anotar.NServiceBus.csproj" />
    <ProjectReference Include="..\AssemblyToProcess\AssemblyToProcess.csproj" />
    <PackageReference Include="Microsoft.CSharp" />
  </ItemGroup>
</Project>